name: Kymatio self-hosted CI

on:
    - push
    - pull_request

jobs:
    build:
        runs-on: [self-hosted, gpu]

        strategy:
            matrix:
                python-version: [3.6, 3.7]
                pytorch-version: [1.7.0, 1.8]

        steps:
            - uses: actions/checkout@v1
            - name: Add Conda to path
              run: echo $CONDA >> $GITHUB_PATH
            - name: Set up Conda
              run: |
                  conda config --set always_yes yes --set changeps1 no

                  conda update -q conda

                  conda info -a

                  conda create -q -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python=${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  conda install -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} numpy scipy pytest pytest-cov
                  conda install -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} pytorch==${{ matrix.pytorch-version }} torchvision torchaudio cudatoolkit=10.2 -c pytorch

                  conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 -m pip install --upgrade pip

                  conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 -m pip install "tensorflow>=2.0.0a"
                  conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 -m pip install scikit-learn

                  conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 -m pip install -r requirements.txt
                  conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 -m pip install -r requirements_optional.txt
            - name: Set up Kymatio
              run: conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} python3 setup.py develop
            - name: Test Torch
              run: conda run -n test-env-${{ matrix.python-version }}-${{ matrix.pytorch-version }} pytest tests/scattering*d/*torch*.py
