name: Kymatio CI

on:
    - push
    - pull_request

jobs:
    build-pip:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v1
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install pytest pytest-cov

                  torch_version="1.7.1+cpu"
                  torchvision_version="0.8.2+cpu"

                  python3 -m pip install torch==${torch_version} torchvision==${torchvision_version} -f https://download.pytorch.org/whl/torch_stable.html

                  if [ "${{ matrix.python-version }}" != "3.9" ]; then
                      python3 -m pip install "tensorflow>=2.0.0a"
                  fi

                  python3 -m pip install scikit-learn

                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements_optional.txt
            - name: Set up Kymatio
              run: python3 setup.py develop
            - name: Test
              run: pytest --cov=kymatio

    build-conda:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v1
            - name: Add Conda to path
              run: echo $CONDA >> $GITHUB_PATH
            - name: Set up Conda
              run: |
                  conda config --set always_yes yes --set changeps1 no

                  conda update -q conda

                  conda info -a

                  conda create -q -n test-env python=${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  conda install -n test-env numpy scipy pytest pytest-cov

                  if [ "${{ matrix.python-version }}" = "3.9" ]; then
                      # For py39, we need to override some standard conda
                      # packages (see https://pytorch.org/get-started/locally/)
                      channel="-c conda-forge"
                  else
                      channel=""
                  fi

                  conda install -n test-env pytorch torchvision cpuonly -c pytorch ${channel}

                  conda run -n test-env python3 -m pip install --upgrade pip

                  if [ "${{ matrix.python-version }}" != "3.9" ]; then
                      conda run -n test-env python3 -m pip install "tensorflow>=2.0.0a"
                  fi

                  conda run -n test-env python3 -m pip install scikit-learn

                  conda run -n test-env python3 -m pip install -r requirements.txt
                  conda run -n test-env python3 -m pip install -r requirements_optional.txt
            - name: Set up Kymatio
              run: conda run -n test-env python3 setup.py develop
            - name: Test
              run: conda run -n test-env pytest --cov=kymatio
