name: Kymatio Slurm CI

on:
    - push
    - pull_request
jobs:
    enqueue:
        runs-on: [self-hosted, slurm]
        steps:
            - uses: actions/checkout@v1
            - name: Get a short version of the GIT commit SHA to use in naming files
              id: getshortsha
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Run scripts on slurm
              run: |
                  JOB_MSG=$(sbatch --wait .github/workflows/slurm_conda.sh ${{ steps.getshortsha.outputs.sha_short }})
                  JOB_ID=${JOB_MSG##* }
                  echo "Error message"
                  cat kymatio-${JOB_ID}.err
                  echo "Output message"
                  cat kymatio-${JOB_ID}.out
