name: Kymatio Slurm CI

on:
    - push
    - pull_request
jobs:
    enqueue:
        runs-on: [self-hosted, slurm]
        steps:
            - uses: actions/checkout@v1
            - name: Get a short version of the GIT commit SHA to use in naming files
              id: getshortsha
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Run scripts on slurm
              run: |
                  export JOB_MSG=$(sbatch --wait .github/workflows/slurm_conda.sh ${{ steps.getshortsha.outputs.sha_short }})
                  echo "::set-output name=job_id::${JOB_MSG##* }"
                  echo "Error message"
                  cat kymatio-${{ steps.getshortsha.outputs.job_id }}.err
                  echo "Output message"
                  cat kymatio-${{ steps.getshortsha.outputs.job_id }}.out
            - name: If the job has failed
              if: ${{ cancelled() }}
              run: |
                  scancel ${{ steps.getshortsha.outputs.job_id }}
                  conda env remove --name ${{ steps.getshortsha.outputs.job_id }}
