name: Kymatio Slurm CI

on:
    - push
    - pull_request


jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get a short version of the GIT commit SHA to use in naming files
        id: getshortsha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Run scripts on slurm
              run: |
                cd "your-directory/${{ steps.getshortsha.outputs.sha_short }}"
                mv job-sbatcher.sh ${{ steps.getshortsha.outputs.sha_short }}-job-sbatcher.sh
                sbatch ${{ steps.getshortsha.outputs.sha_short }}-job-sbatcher.sh.sh