name: Kymatio Slurm CI

on:
    - push
    - pull_request
jobs:
    build:
        runs-on: [self-hosted, slurm] #enqueue:
    steps:
      - uses: actions/checkout@v1
      - name: Get a short version of the GIT commit SHA to use in naming files
        id: getshortsha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Run scripts on slurm
              run: |
                sbatch slurm_conda.sh ${{ steps.getshortsha.outputs.sha_short }}

